- block:
  - name: instalacja selinux-python
    yum:
      name: libselinux-python
      state: present
  
  - name: Instalacja nginx
    yum:
      name: nginx
      state: present

  - name: Dodawanie portu do php do selinuxa
    seport:
      ports: 9005
      proto: tcp
      setype: http_port_t
      state: present

  - name: Uruchamianie nginx
    service:
      name: nginx
      state: started
      enabled: True

  - name: wgrywanie konfiguracji
    copy:
      src: app1.conf
      dest: /etc/nginx/conf.d/app1.conf
    notify:
    - restart_nginx

  become: True
  become_user: root
