- block:
  - name: instalacja selinux-python
    yum:
      name: libselinux-python
      state: present
  
  - name: Instalacja nginx
    yum:
      name: nginx
      state: present

  - name: Dodawanie portu do php do selinuxa
    seport:
      ports: "{{item.value.fcgi_port}}"
      proto: tcp
      setype: http_port_t
      state: present
    with_dict: "{{apps}}"

  - name: wgrywanie konfiguracji
    template:
      src: apps.conf.j2
      dest: /etc/nginx/conf.d/apps.conf
    notify:
    - restart_nginx

  - name: tworzenie katalogow na document root
    file:
      path: "{{item.value.root}}"
      state: directory
    with_dict: "{{apps}}"

  - name: Uruchamianie nginx
    service:
      name: nginx
      state: started
      enabled: True


  become: True
  become_user: root
