- block:
  - name: Instalacja haproxy
    yum:
      name: haproxy
      state: present

  - name: Dodawanie portow do selinuxa
    seport:
      ports: "{{item.value.listen_port}}"
      proto: tcp
      setype: http_port_t
      state: present
    notify:
    - restart_haproxy
    with_dict: "{{apps}}"

  - name: Wgrywanie konfiguracji
    template:
      src: haproxy.cfg
      dest: /etc/haproxy/
    notify:
    - restart_haproxy

  - name: Uruchamianie haproxy
    service:
      name: haproxy
      state: started
      enabled: True


  become: True
  become_user: root
