- block:
  - name: Instalacja haproxy
    yum:
      name: haproxy
      state: present

  - name: Dodawanie portu do selinuxa
    seport:
      ports: 8001
      proto: tcp
      setype: http_port_t
      state: present
    notify:
    - restart_haproxy

  - name: Uruchamianie haproxy
    service:
      name: haproxy
      state: started
      enabled: True

  - name: Wgrywanie konfiguracji
    copy:
      src: haproxy.cfg
      dest: /etc/haproxy/
    notify:
    - restart_haproxy

  become: True
  become_user: root
