- block:
  - name: Instalacja php-fpm
    yum:
      name: php-fpm
      state: present
  
  - name: Dodawanie portu 9005 do selinuxa
    seport:
      ports: 9005
      proto: tcp
      setype: http_port_t
      state: present
    notify:
    - restart_php-fpm

  - name: Uruchamianie php-fpm
    service:
      name: php-fpm
      state: started
      enabled: True

  - name: wgrywanie konfiguracji
    copy:
      src: app1.conf
      dest: /etc/php-fpm.d/
    notify:
    - restart_php-fpm

  become: True
  become_user: root
