- block:
  - name: Instalacja php-fpm
    yum:
      name: php-fpm
      state: present
  
  - name: Dodawanie portow do selinuxa
    seport:
      ports: "{{item.value.fcgi_port}}"
      proto: tcp
      setype: http_port_t
      state: present
    notify:
    - restart_php-fpm
    with_dict: "{{apps}}"

  - name: wgrywanie konfiguracji
    template:
      src: apps.conf
      dest: /etc/php-fpm.d/
    notify:
    - restart_php-fpm

  - name: Uruchamianie php-fpm
    service:
      name: php-fpm
      state: started
      enabled: True


  become: True
  become_user: root
