- block:
  - name: Instalacja php-fpm
    yum:
      name: php-fpm
      state: present
  
  - name: Dodawanie portow do selinuxa
    seport:
      ports: "{{item.value.fpm.port}}"
      proto: tcp
      setype: http_port_t
      state: present
    notify:
    - restart_php-fpm
    with_dict: "{{apps}}"

  - name: wgrywanie konfiguracji
    template:
      src: apps.conf
      dest: /etc/php-fpm.d/
    notify:
    - restart_php-fpm

  - name: Uruchamianie php-fpm
    service:
      name: php-fpm
      state: started
      enabled: True


  become: True
  become_user: root

- include_role:
    name: app_deploy
  vars:
    app: "{{item.value.fpm.app|combine({'name': item.key, 'dest': '/var/www/'})}}"
  with_dict: "{{apps}}"
  when: item.value.fpm is defined

