- block:
  - name: instalacja epel
    yum:
      name: epel-release
      state: present

  - name: instalacja policycoreutils
    yum:
      name: policycoreutils-python
      state: present

#  - selinux:
#      policy: targeted
#      state: enforcing

  become: True
  become_user: root

